project:
  type: manuscript
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!slides/"
    - "!_ing"

manuscript:
  article: NBA_2023-24.ipynb

bibliography: references.bib
link-citations: true

format:
  html:
    toc: true
    comments:
      hypothesis: true
  pdf:
    documentclass: scrreprt
    papersize: a4
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{kotex}